/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Lex AI",
  "tagline": "Lex AI – community-driven platform for Machine Learning, Deep Learning, and Language Models",
  "favicon": "img/lexai-logo.svg",
  "url": "https://ai-ml-docs.org",
  "baseUrl": "/",
  "organizationName": "ai-ml-community",
  "projectName": "ai-ml-docs",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "editUrl": "https://github.com/ai-ml-community/ai-ml-docs/tree/main/",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/ai-ml-community/ai-ml-docs/tree/main/",
          "remarkPlugins": [
            null
          ],
          "rehypePlugins": [
            null
          ]
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/social-card.jpg",
    "navbar": {
      "logo": {
        "alt": "Lex AI",
        "src": "img/lexai-logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "docsSidebar",
          "position": "left",
          "label": "Resources"
        },
        {
          "type": "dropdown",
          "label": "Topics",
          "position": "left",
          "items": [
            {
              "label": "AI for Leaders",
              "to": "/docs/ai-for-leaders/intro"
            },
            {
              "label": "Machine Learning",
              "to": "/docs/machine-learning/intro"
            },
            {
              "label": "Deep Learning",
              "to": "/docs/deep-learning/intro"
            },
            {
              "label": "Language Models",
              "to": "/docs/language-models/intro"
            },
            {
              "label": "Resources",
              "to": "/docs/resources/intro"
            }
          ]
        },
        {
          "to": "/fellowship",
          "label": "AI Fellowship",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "Tutorials",
          "position": "left",
          "items": [
            {
              "label": "Interactive Logistic Regression",
              "to": "/docs/tutorials/logistic-regression"
            }
          ]
        },
        {
          "href": "https://github.com/ai-ml-community/ai-ml-docs",
          "label": "GitHub",
          "position": "right"
        },
        {
          "to": "/contribute",
          "label": "Contribute",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "AI for Leaders",
              "to": "/docs/ai-for-leaders/intro"
            },
            {
              "label": "Machine Learning",
              "to": "/docs/machine-learning/intro"
            },
            {
              "label": "Deep Learning",
              "to": "/docs/deep-learning/intro"
            },
            {
              "label": "Language Models",
              "to": "/docs/language-models/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub Discussions",
              "href": "https://github.com/ai-ml-community/ai-ml-docs/discussions"
            },
            {
              "label": "Join our Discord community here",
              "href": "https://discord.gg/QtzYHmfw"
            },
            {
              "label": "Twitter",
              "href": "https://x.com/labs_ai80315"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "Blog",
              "to": "/blog"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/ai-ml-community/ai-ml-docs"
            },
            {
              "label": "Contribute",
              "to": "/contribute"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Lex AI Technologies Pvt Ltd. 🌏❤️ Proudly built in India 🇮🇳"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "python",
        "r",
        "julia"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "stylesheets": [
      {
        "href": "https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css",
        "type": "text/css",
        "integrity": "sha384-mQ93GR66B8fYB1+K+9a6UA+6QK9lQ8l+Q5p3p3Z5p3p3Z5p3p3Z5p3p3Z5p3p3Z5",
        "crossorigin": "anonymous"
      },
      {
        "href": "https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&family=Lora:wght@400;500;600;700&display=swap",
        "type": "text/css"
      }
    ],
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
